// Mock data for SCA Risk Intelligence dashboard.
// All hardcoded — no APIs, no storage.

export const dataSources = [
  { id: 'erp',   name: 'ERP Systems',          subtitle: 'SAP S/4 · Oracle EBS',     status: 'green', last: '4 min ago',  records: '14,820 records', icon: 'Database' },
  { id: 'tpr',   name: 'Third-Party Risk Tool', subtitle: 'RiskMethods · Resilinc',  status: 'green', last: '12 min ago', records: '2,341 records',  icon: 'Shield' },
  { id: 'ddl',   name: 'DDL Feeds',             subtitle: 'Denied / restricted lists', status: 'amber', last: '38 min ago', records: '987 records',    icon: 'Globe' },
  { id: 'docs',  name: 'Written Reports & PDFs', subtitle: 'Audit reports · NDAs',    status: 'green', last: '8 min ago',  records: '412 documents',  icon: 'FileText' },
  { id: 'rev',   name: 'Revenue Consolidation', subtitle: 'BU spend · contracts',    status: 'red',   last: '2 hr ago',   records: 'Sync failed',     icon: 'DollarSign' },
];

// Risk category metadata
export const categories = {
  Compliance:    { icon: 'Shield',        tint: 'text-violet-300',  ring: 'ring-violet-400/30',  label: 'Compliance',   sub: 'RBA audit' },
  Financial:     { icon: 'DollarSign',    tint: 'text-amber-300',   ring: 'ring-amber-400/30',   label: 'Financial',    sub: 'Credit / bankruptcy' },
  Operational:   { icon: 'Package',       tint: 'text-sky-300',     ring: 'ring-sky-400/30',     label: 'Operational',  sub: 'Capacity / delivery' },
  Geopolitical:  { icon: 'Globe',         tint: 'text-rose-300',    ring: 'ring-rose-400/30',    label: 'Geopolitical', sub: 'Sanctions / conflict' },
  Cyber:         { icon: 'Cpu',           tint: 'text-cyan-300',    ring: 'ring-cyan-400/30',    label: 'Cyber',        sub: 'Breach / vulnerability' },
  Environmental: { icon: 'Leaf',          tint: 'text-emerald-300', ring: 'ring-emerald-400/30', label: 'Environmental',sub: 'Emissions / hazardous' },
};

export const risks = [
  {
    id: 'r-001', supplier: 'Foxconn',        country: 'TW', category: 'Geopolitical',
    severity: 'Critical', source: 'DDL Feeds', confidence: 94, action: 'Escalate', status: 'New',
    detected: 'May 8',
    summary: 'Cross-strait military exercises announced near Foxconn\'s Kaohsiung assembly cluster, with shipping lane advisories issued by Taiwan MOTC. Carrier rerouting could delay outbound finished goods by 11–18 days at current inventory burn.',
    reasoning: 'Single-source server motherboard line + DDL geopolitical advisory + <20 day inventory buffer.',
    products: ['PowerEdge R760', 'PowerEdge XE9680', 'Precision 7960'],
    altSupplier: null, // single source
    revenueExposure: '$148M',
    daysToImpact: 14,
    chain: ['Foxconn (T1 assembly)', 'Murata (T2 capacitors)', 'DRC tantalum (raw)'],
    recommendation: 'Escalate — single-source supplier with $148M quarterly exposure and 14-day inventory buffer. Activate dual-source qualification with Quanta in parallel.',
    audit: [
      { t: 'May 8 · 06:14', who: 'DDL Feed',     act: 'Auto-detected geopolitical advisory (TW)', kind: 'system' },
      { t: 'May 8 · 06:14', who: 'Risk Engine',  act: 'AI-scored Critical (94% confidence)',     kind: 'ai' },
      { t: 'May 8 · 09:02', who: 'Sarah Chen',   act: 'Triaged · attached to active investigation', kind: 'human' },
      { t: 'May 9 · 11:47', who: 'M. Okafor',    act: 'Pending leadership escalation review',    kind: 'human' },
    ],
  },
  {
    id: 'r-002', supplier: 'Quanta Computer', country: 'TW', category: 'Operational',
    severity: 'High', source: 'ERP Systems', confidence: 88, action: 'Investigate', status: 'In Review',
    detected: 'May 8',
    summary: 'Quanta\'s Chongqing line reporting 31% capacity utilization vs. 78% contracted floor for Q2. ERP open-PO aging shows 2,140 units past commit date across two SKUs.',
    reasoning: 'Capacity gap + 14-day commit slip + recurring pattern over last 3 weeks.',
    products: ['Latitude 7450', 'Latitude 5550'],
    altSupplier: { name: 'Compal Electronics', leadDays: 60 },
    revenueExposure: '$42M',
    daysToImpact: 22,
    chain: ['Quanta (T1 ODM)', 'BOE Display (T2 panels)', 'Corning (raw glass)'],
    recommendation: 'Investigate — capacity recovery plan due from Quanta by EOW. Hold escalation pending response; Compal qualified as backup.',
    audit: [
      { t: 'May 7 · 22:01', who: 'ERP Systems',  act: 'Detected commit-date slip on PO #44218', kind: 'system' },
      { t: 'May 8 · 04:30', who: 'Risk Engine',  act: 'AI-scored High (88% confidence)',         kind: 'ai' },
      { t: 'May 8 · 13:12', who: 'D. Patel',     act: 'Assigned to operations team',             kind: 'human' },
    ],
  },
  {
    id: 'r-003', supplier: 'Celestica',       country: 'CA', category: 'Financial',
    severity: 'Medium', source: 'Third-Party Risk Tool', confidence: 76, action: 'Monitor', status: 'New',
    detected: 'May 9',
    summary: 'Resilinc credit watchlist downgraded Celestica subsidiary in Thailand from BBB to BBB- citing FX exposure. Parent rating unchanged; subsidiary handles 18% of total Celestica volume to our BUs.',
    reasoning: 'Subsidiary-level only · parent unaffected · low contagion probability.',
    products: ['OptiPlex 7020', 'PowerEdge R660'],
    altSupplier: { name: 'Jabil', leadDays: 45 },
    revenueExposure: '$18M',
    daysToImpact: 60,
    chain: ['Celestica TH (T1)', 'Murata JP (T2)', 'Asahi Kasei (raw)'],
    recommendation: 'Monitor — schedule weekly credit review. No action required while parent rating holds.',
    audit: [
      { t: 'May 9 · 02:18', who: 'Resilinc',    act: 'Credit watchlist update ingested', kind: 'system' },
      { t: 'May 9 · 02:18', who: 'Risk Engine', act: 'AI-scored Medium (76% confidence)', kind: 'ai' },
    ],
  },
  {
    id: 'r-004', supplier: 'Jabil',           country: 'US', category: 'Cyber',
    severity: 'High', source: 'Third-Party Risk Tool', confidence: 91, action: 'Escalate', status: 'Escalated',
    detected: 'May 7',
    summary: 'Reported intrusion at Jabil\'s Penang facility EDI gateway. Forensics indicate 4-hour exposure window on Friday; PO and BOM tables flagged for review.',
    reasoning: 'Active intrusion · shared EDI surface with our procurement · CISO notified.',
    products: ['Latitude 7450', 'OptiPlex 5400'],
    altSupplier: { name: 'Flex (Flextronics)', leadDays: 50 },
    revenueExposure: '$67M',
    daysToImpact: 35,
    chain: ['Jabil PEN (T1)', 'TSMC (T2 silicon)', 'ASE (T2 packaging)'],
    recommendation: 'Escalate — confirm BOM exfiltration scope; rotate EDI credentials; CISO + Procurement Director joint review.',
    audit: [
      { t: 'May 7 · 18:44', who: 'RiskMethods', act: 'Cyber incident bulletin received',  kind: 'system' },
      { t: 'May 7 · 18:45', who: 'Risk Engine', act: 'AI-scored High (91% confidence)',   kind: 'ai' },
      { t: 'May 7 · 20:10', who: 'A. Rivera',   act: 'Escalated to Director · CISO loop', kind: 'human' },
      { t: 'May 8 · 09:30', who: 'CISO Office', act: 'Joint review scheduled May 10',     kind: 'human' },
    ],
  },
  {
    id: 'r-005', supplier: 'Pegatron',         country: 'TW', category: 'Compliance',
    severity: 'Medium', source: 'Written Reports & PDFs', confidence: 82, action: 'Investigate', status: 'In Review',
    detected: 'May 6',
    summary: 'RBA audit report (April) flagged 2 minor non-conformances on working-hours documentation at Suzhou plant. Corrective action plan submitted; closure pending verification.',
    reasoning: 'Minor findings · CAP active · low recurrence risk.',
    products: ['XPS 13', 'XPS 15'],
    altSupplier: { name: 'Wistron', leadDays: 75 },
    revenueExposure: '$28M',
    daysToImpact: 90,
    chain: ['Pegatron (T1)', 'AUO (T2 panels)', 'Corning (raw)'],
    recommendation: 'Investigate — verify CAP closure on next audit cycle. No supply impact expected.',
    audit: [
      { t: 'May 6 · 11:00', who: 'Reports OCR', act: 'RBA audit PDF parsed and indexed', kind: 'system' },
      { t: 'May 6 · 11:01', who: 'Risk Engine', act: 'AI-scored Medium (82% confidence)', kind: 'ai' },
      { t: 'May 6 · 16:22', who: 'L. Nakamura', act: 'Assigned for CAP verification',     kind: 'human' },
    ],
  },
  {
    id: 'r-006', supplier: 'Flex (Flextronics)', country: 'SG', category: 'Operational',
    severity: 'Low', source: 'ERP Systems', confidence: 71, action: 'Monitor', status: 'Resolved',
    detected: 'May 4',
    summary: 'Brief shipping delay at Guadalajara plant due to local port congestion; recovered May 6. Net OTIF impact: -1.2 pts week-over-week.',
    reasoning: 'Resolved · within tolerance · no inventory impact.',
    products: ['PowerEdge R660', 'PowerStore 1000'],
    altSupplier: { name: 'Jabil', leadDays: 45 },
    revenueExposure: '$4M',
    daysToImpact: null,
    chain: ['Flex (T1)', 'Sanmina (T2)', 'Various (raw)'],
    recommendation: 'Monitor — close-out scheduled. Trend within tolerance band.',
    audit: [
      { t: 'May 4 · 07:12', who: 'ERP Systems',  act: 'OTIF anomaly detected', kind: 'system' },
      { t: 'May 4 · 07:13', who: 'Risk Engine',  act: 'AI-scored Low (71%)',   kind: 'ai' },
      { t: 'May 6 · 14:00', who: 'M. Okafor',    act: 'Marked resolved',       kind: 'human' },
    ],
  },
  {
    id: 'r-007', supplier: 'Compal',           country: 'TW', category: 'Environmental',
    severity: 'Medium', source: 'Written Reports & PDFs', confidence: 79, action: 'Investigate', status: 'New',
    detected: 'May 9',
    summary: 'Q1 Scope-3 emissions self-report shows 8% YoY increase, exceeding our supplier sustainability commitment band. Energy intensity metrics on our share of volume up 11%.',
    reasoning: 'Outside committed band · ESG team review required.',
    products: ['Latitude 5550', 'Vostro 3520'],
    altSupplier: { name: 'Quanta', leadDays: 60 },
    revenueExposure: '$22M',
    daysToImpact: null,
    chain: ['Compal (T1)', 'Innolux (T2 panels)', 'Corning (raw)'],
    recommendation: 'Investigate — request remediation roadmap; ESG joint scorecard review.',
    audit: [
      { t: 'May 9 · 03:44', who: 'Reports OCR', act: 'ESG report parsed',          kind: 'system' },
      { t: 'May 9 · 03:45', who: 'Risk Engine', act: 'AI-scored Medium (79%)',     kind: 'ai' },
    ],
  },
  {
    id: 'r-008', supplier: 'Wistron',          country: 'TW', category: 'Financial',
    severity: 'High', source: 'Revenue Consolidation', confidence: 86, action: 'Escalate', status: 'New',
    detected: 'May 9',
    summary: 'Concentration analysis: our spend now represents 23% of Wistron\'s notebook ODM revenue, breaching our 20% concentration policy. Wistron renegotiating terms.',
    reasoning: 'Policy breach · leverage asymmetry · contract renewal in 6 weeks.',
    products: ['Latitude 7450', 'Precision 3590'],
    altSupplier: { name: 'Pegatron', leadDays: 75 },
    revenueExposure: '$54M',
    daysToImpact: 42,
    chain: ['Wistron (T1)', 'AUO (T2 panels)', 'Corning (raw)'],
    recommendation: 'Escalate — concentration risk + active negotiation. Procurement + Finance joint review.',
    audit: [
      { t: 'May 9 · 01:22', who: 'Rev. Consol.', act: 'Concentration breach computed', kind: 'system' },
      { t: 'May 9 · 01:23', who: 'Risk Engine',  act: 'AI-scored High (86%)',          kind: 'ai' },
    ],
  },
  {
    id: 'r-009', supplier: 'Delta Electronics', country: 'TW', category: 'Cyber',
    severity: 'Critical', source: 'Third-Party Risk Tool', confidence: 96, action: 'Escalate', status: 'New',
    detected: 'May 9',
    summary: 'Zero-day vulnerability disclosed in Delta\'s industrial control firmware affecting power supplies shipped Q1–Q2 2026. CVSS 9.4. Patch ETA 5–7 business days.',
    reasoning: 'Active CVE · downstream products in production · CVSS 9.4.',
    products: ['PowerEdge R760', 'PowerEdge XE9680', 'Latitude 7450'],
    altSupplier: null,
    revenueExposure: '$92M',
    daysToImpact: 7,
    chain: ['Delta (T1 PSU)', 'TI / Infineon (T2 ICs)', 'Various (raw)'],
    recommendation: 'Escalate — single-source critical CVE. Stop-ship hold pending patch verification; CISO + Engineering joint review.',
    audit: [
      { t: 'May 9 · 00:08', who: 'RiskMethods', act: 'CVE-2026-1184 bulletin ingested', kind: 'system' },
      { t: 'May 9 · 00:08', who: 'Risk Engine', act: 'AI-scored Critical (96%)',         kind: 'ai' },
    ],
  },
  {
    id: 'r-010', supplier: 'Lite-On',          country: 'TW', category: 'Geopolitical',
    severity: 'Low', source: 'DDL Feeds', confidence: 68, action: 'Monitor', status: 'New',
    detected: 'May 8',
    summary: 'Trade-policy advisory: tariff schedule update affecting select power-supply HS codes. Lite-On exposure 4% of category spend.',
    reasoning: 'Low spend share · tariff already passed-through in latest quote.',
    products: ['Vostro 3520'],
    altSupplier: { name: 'Delta', leadDays: 30 },
    revenueExposure: '$3M',
    daysToImpact: null,
    chain: ['Lite-On (T1)', 'Various (T2)', 'Various (raw)'],
    recommendation: 'Monitor — incorporate into next quarterly tariff review.',
    audit: [
      { t: 'May 8 · 16:40', who: 'DDL Feed',    act: 'Tariff schedule update',  kind: 'system' },
      { t: 'May 8 · 16:41', who: 'Risk Engine', act: 'AI-scored Low (68%)',     kind: 'ai' },
    ],
  },
];

export const supplierDirectory = [
  // Already in queue
  { name: 'Foxconn',           country: 'TW', tier: 'T1', spend: '$1.4B', flagged: true },
  { name: 'Quanta Computer',   country: 'TW', tier: 'T1', spend: '$820M', flagged: true },
  { name: 'Celestica',         country: 'CA', tier: 'T1', spend: '$310M', flagged: true },
  { name: 'Jabil',             country: 'US', tier: 'T1', spend: '$540M', flagged: true },
  { name: 'Pegatron',          country: 'TW', tier: 'T1', spend: '$280M', flagged: true },
  { name: 'Flex (Flextronics)',country: 'SG', tier: 'T1', spend: '$420M', flagged: true },
  { name: 'Compal',            country: 'TW', tier: 'T1', spend: '$240M', flagged: true },
  { name: 'Wistron',           country: 'TW', tier: 'T1', spend: '$390M', flagged: true },
  { name: 'Delta Electronics', country: 'TW', tier: 'T1', spend: '$610M', flagged: true },
  { name: 'Lite-On',           country: 'TW', tier: 'T1', spend: '$140M', flagged: true },
  // Pool — not currently flagged, demonstrates 1,247 search depth
  { name: 'TSMC',              country: 'TW', tier: 'T2', spend: '$2.1B', flagged: false },
  { name: 'Samsung Electronics', country: 'KR', tier: 'T1', spend: '$1.8B', flagged: false },
  { name: 'SK Hynix',          country: 'KR', tier: 'T2', spend: '$680M', flagged: false },
  { name: 'Micron Technology', country: 'US', tier: 'T2', spend: '$520M', flagged: false },
  { name: 'Western Digital',   country: 'US', tier: 'T2', spend: '$310M', flagged: false },
  { name: 'Seagate',           country: 'US', tier: 'T2', spend: '$280M', flagged: false },
  { name: 'Murata',            country: 'JP', tier: 'T2', spend: '$190M', flagged: false },
  { name: 'BOE Display',       country: 'CN', tier: 'T2', spend: '$240M', flagged: false },
  { name: 'AUO',               country: 'TW', tier: 'T2', spend: '$160M', flagged: false },
  { name: 'Sanmina',           country: 'US', tier: 'T1', spend: '$120M', flagged: false },
  { name: 'Inventec',          country: 'TW', tier: 'T1', spend: '$210M', flagged: false },
  { name: 'New Kinpo Group',   country: 'TW', tier: 'T1', spend: '$95M',  flagged: false },
  { name: 'TPV Technology',    country: 'CN', tier: 'T1', spend: '$110M', flagged: false },
  { name: 'Asustek',           country: 'TW', tier: 'T1', spend: '$80M',  flagged: false },
  { name: 'Lenovo (OEM div.)', country: 'CN', tier: 'T1', spend: '$70M',  flagged: false },
];
